### ISSUE TITLE
BioSim integration

### ISSUE THREAD

**Issue by achubaty** [achubaty/MPB#14]
After following up with Remi, we have a means to invoke BioSim from the commandline by passing the `-e` option using [BioSim11](ftp://ftp.cfl.scf.rncan.gc.ca/regniere/software/BioSIM/BioSIM11_x_x.7z).

@BarryCooke will recreate/import the necessary project (XML) files to produce the MPB climatic suitability projections using each of the previously used indices (R, S, L, G) plus the MPB iMod index (I?).

Use the [`BioSim/`](https://github.com/achubaty/MPB/tree/master/BioSim) directory for these files.

See also #4

**Comment by achubaty** [comment]
AFAIK this has yet to be implemented/worked out. @BarryCooke any chance you could revisit/followup ot this?

**Comment by eliotmcintire** [comment]
The most likely thing is now from Mathieu Fortin, CFS scientist.

**Comment by achubaty** [comment]
Looks like Mathieu Fortin's `BioSIM` R package is the way to go:

https://sourceforge.net/p/mrnfforesttools/biosimclient/wiki/BioSIM-R/

Closing this.
